apiVersion: v1
kind: Pod
metadata:
  namespace: petclinic-dev
  labels:
    component: jenkins-agent
spec:
  containers:
  - name: maven
    image: 'maven:3.6.3-adoptopenjdk-11'
    command:
    - cat
    tty: true
  - name: docker
    image: docker:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - cat
    tty: true
  serviceAccountName: petclinic-sa
  securityContext:
    runAsUser: 0
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
